version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build Docker image...
      - docker build -t rag-api:latest .
      - docker tag rag-api:latest 675266034256.dkr.ecr.us-east-1.amazonaws.com/rag-api:latest
  post_build:
    commands:
      - echo Push Docker image to ECR...
      - docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/rag-api:latest

artifacts:
  files:
    - '**/*'
